# FIPS Node {{NODE_NAME}} configuration ({{TOPOLOGY}} topology)
#
# Identity: {{NPUB}}

node:
  identity:
    nsec: "{{NSEC}}"

tun:
  enabled: true
  name: fips0
  mtu: 1280

dns:
  enabled: true
  bind_addr: "127.0.0.1"

transports:
  udp:
    bind_addr: "0.0.0.0:4000"
    mtu: 1472

peers:
{{PEERS}}